In [1]:
import pandas as pd

In [2]:
df_1 = pd.read_csv("1- mental-illnesses-prevalence.csv")
df_1

,Entity,Code,Year,Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized,Depressive disorders (share of population) - Sex: Both - Age: Age-standardized,Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized,Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized,Eating disorders (share of population) - Sex: Both - Age: Age-standardized
0,Afghanistan,AFG,1990,0.223206,4.996118,4.713314,0.703023,0.127700
1,Afghanistan,AFG,1991,0.222454,4.989290,4.702100,0.702069,0.123256
2,Afghanistan,AFG,1992,0.221751,4.981346,4.683743,0.700792,0.118844
3,Afghanistan,AFG,1993,0.220987,4.976958,4.673549,0.700087,0.115089
4,Afghanistan,AFG,1994,0.220183,4.977782,4.670810,0.699898,0.111815
...,...,...,...,...,...,...,...,...
6415,Zimbabwe,ZWE,2015,0.201042,3.407624,3.184012,0.538596,0.095652
6416,Zimbabwe,ZWE,2016,0.201319,3.410755,3.187148,0.538593,0.096662
6417,Zimbabwe,ZWE,2017,0.201639,3.411965,3.188418,0.538589,0.097330
6418,Zimbabwe,ZWE,2018,0.201976,3.406929,3.172111,0.538585,0.097909
6419,Zimbabwe,ZWE,2019,0.202482,3.395476,3.137017,0.538580,0.098295

In [3]:
df_2 = pd.read_csv("2- burden-disease-from-each-mental-illness(1).csv")
df_2

,Entity,Code,Year,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Depressive disorders,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Schizophrenia,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Bipolar disorder,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Eating disorders,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Anxiety disorders
0,Afghanistan,AFG,1990,895.22565,138.248250,147.64412,26.471115,440.33000
1,Afghanistan,AFG,1991,893.88434,137.761220,147.56696,25.548681,439.47202
2,Afghanistan,AFG,1992,892.34973,137.080300,147.13086,24.637949,437.60718
3,Afghanistan,AFG,1993,891.51587,136.486020,146.78812,23.863169,436.69104
4,Afghanistan,AFG,1994,891.39160,136.183230,146.58481,23.189074,436.76800
...,...,...,...,...,...,...,...,...
6835,Zimbabwe,ZWE,2015,546.46204,127.108720,115.32073,20.423056,302.20868
6836,Zimbabwe,ZWE,2016,547.27765,127.142105,114.98700,20.647228,302.68216
6837,Zimbabwe,ZWE,2017,547.62270,127.465050,115.32798,20.791725,302.88626
6838,Zimbabwe,ZWE,2018,546.57184,127.681210,115.42796,20.916480,301.58250
6839,Zimbabwe,ZWE,2019,544.53160,128.216030,115.38145,21.011127,298.20325

In [6]:
combo = df_1.merge(df_2, how= "inner", on=["Entity","Code","Year"])
combo

,Entity,Code,Year,Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized,Depressive disorders (share of population) - Sex: Both - Age: Age-standardized,Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized,Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized,Eating disorders (share of population) - Sex: Both - Age: Age-standardized,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Depressive disorders,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Schizophrenia,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Bipolar disorder,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Eating disorders,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Anxiety disorders
0,Afghanistan,AFG,1990,0.223206,4.996118,4.713314,0.703023,0.127700,895.22565,138.248250,147.64412,26.471115,440.33000
1,Afghanistan,AFG,1991,0.222454,4.989290,4.702100,0.702069,0.123256,893.88434,137.761220,147.56696,25.548681,439.47202
2,Afghanistan,AFG,1992,0.221751,4.981346,4.683743,0.700792,0.118844,892.34973,137.080300,147.13086,24.637949,437.60718
3,Afghanistan,AFG,1993,0.220987,4.976958,4.673549,0.700087,0.115089,891.51587,136.486020,146.78812,23.863169,436.69104
4,Afghanistan,AFG,1994,0.220183,4.977782,4.670810,0.699898,0.111815,891.39160,136.183230,146.58481,23.189074,436.76800
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6145,Zimbabwe,ZWE,2015,0.201042,3.407624,3.184012,0.538596,0.095652,546.46204,127.108720,115.32073,20.423056,302.20868
6146,Zimbabwe,ZWE,2016,0.201319,3.410755,3.187148,0.538593,0.096662,547.27765,127.142105,114.98700,20.647228,302.68216
6147,Zimbabwe,ZWE,2017,0.201639,3.411965,3.188418,0.538589,0.097330,547.62270,127.465050,115.32798,20.791725,302.88626
6148,Zimbabwe,ZWE,2018,0.201976,3.406929,3.172111,0.538585,0.097909,546.57184,127.681210,115.42796,20.916480,301.58250
6149,Zimbabwe,ZWE,2019,0.202482,3.395476,3.137017,0.538580,0.098295,544.53160,128.216030,115.38145,21.011127,298.20325

In [7]:
combo = combo.loc[combo["Year"]==2014]
combo

,Entity,Code,Year,Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized,Depressive disorders (share of population) - Sex: Both - Age: Age-standardized,Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized,Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized,Eating disorders (share of population) - Sex: Both - Age: Age-standardized,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Depressive disorders,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Schizophrenia,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Bipolar disorder,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Eating disorders,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Anxiety disorders
24,Afghanistan,AFG,2014,0.217973,4.944629,4.793179,0.699477,0.113495,889.85590,135.684700,148.167500,23.843073,451.59003
54,Albania,ALB,2014,0.286751,2.442242,3.811362,0.542251,0.129683,383.02032,185.335560,117.858180,27.760595,366.39825
84,Algeria,DZA,2014,0.249173,4.075349,4.713199,0.756351,0.204953,725.54520,160.316210,163.815060,43.641144,453.85280
114,American Samoa,ASM,2014,0.306025,2.629008,4.030562,0.279728,0.128546,388.38812,195.037080,59.681910,27.469060,383.72913
144,Andorra,AND,2014,0.286870,3.566997,5.455121,0.935893,0.510544,617.77734,183.411480,201.671420,108.904945,523.37790
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6024,Vietnam,VNM,2014,0.320686,2.472851,2.253840,0.336163,0.086964,360.54868,209.038200,73.104310,18.897383,217.07216
6054,World,OWID_WRL,2014,0.288205,3.420463,3.751248,0.488349,0.166971,574.16740,184.831200,105.123795,35.735710,357.82690
6084,Yemen,YEM,2014,0.230195,4.892699,4.781608,0.725869,0.141371,892.01080,146.573470,155.795410,29.850027,455.84116
6114,Zambia,ZMB,2014,0.211133,4.181477,3.942423,0.574496,0.109823,700.31530,133.596480,122.794430,23.316214,373.39166
6144,Zimbabwe,ZWE,2014,0.200902,3.399114,3.183361,0.538597,0.094608,544.42930,127.065155,115.086830,20.246943,302.20350

In [8]:
combo = combo.drop(index = 6054)
combo

,Entity,Code,Year,Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized,Depressive disorders (share of population) - Sex: Both - Age: Age-standardized,Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized,Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized,Eating disorders (share of population) - Sex: Both - Age: Age-standardized,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Depressive disorders,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Schizophrenia,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Bipolar disorder,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Eating disorders,DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Anxiety disorders
24,Afghanistan,AFG,2014,0.217973,4.944629,4.793179,0.699477,0.113495,889.85590,135.684700,148.16750,23.843073,451.59003
54,Albania,ALB,2014,0.286751,2.442242,3.811362,0.542251,0.129683,383.02032,185.335560,117.85818,27.760595,366.39825
84,Algeria,DZA,2014,0.249173,4.075349,4.713199,0.756351,0.204953,725.54520,160.316210,163.81506,43.641144,453.85280
114,American Samoa,ASM,2014,0.306025,2.629008,4.030562,0.279728,0.128546,388.38812,195.037080,59.68191,27.469060,383.72913
144,Andorra,AND,2014,0.286870,3.566997,5.455121,0.935893,0.510544,617.77734,183.411480,201.67142,108.904945,523.37790
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5994,Venezuela,VEN,2014,0.279606,3.191789,3.920166,0.828618,0.225608,563.95886,179.544070,179.96196,48.118435,376.02850
6024,Vietnam,VNM,2014,0.320686,2.472851,2.253840,0.336163,0.086964,360.54868,209.038200,73.10431,18.897383,217.07216
6084,Yemen,YEM,2014,0.230195,4.892699,4.781608,0.725869,0.141371,892.01080,146.573470,155.79541,29.850027,455.84116
6114,Zambia,ZMB,2014,0.211133,4.181477,3.942423,0.574496,0.109823,700.31530,133.596480,122.79443,23.316214,373.39166
6144,Zimbabwe,ZWE,2014,0.200902,3.399114,3.183361,0.538597,0.094608,544.42930,127.065155,115.08683,20.246943,302.20350

In [9]:
combo.isna().count()

Entity                                                                               204
Code                                                                                 204
Year                                                                                 204
Schizophrenia disorders (share of population) - Sex: Both - Age: Age-standardized    204
Depressive disorders (share of population) - Sex: Both - Age: Age-standardized       204
Anxiety disorders (share of population) - Sex: Both - Age: Age-standardized          204
Bipolar disorders (share of population) - Sex: Both - Age: Age-standardized          204
Eating disorders (share of population) - Sex: Both - Age: Age-standardized           204
DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Depressive disorders       204
DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Schizophrenia              204
DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Bipolar disorder           204
DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Eating disorders           204
DALYs (rate) - Sex: Both - Age: Age-standardized - Cause: Anxiety disorders          204
dtype: int64

In [10]:
combo.to_csv("tableau.csv", index = False)